networks:
  server_network:

services:
  # Backend - FastAPI
  backend:
    build:
      context: ./RestAPI
      dockerfile: ./Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - /app/.venv/
      - ./RestAPI/:/app/
    env_file:
      - ./pps.env
    networks:
      - server_network
  # Frontend App
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - server_network
    depends_on:
      - backend