networks:
  server_network:

services:
  # Banckend
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - /app/.venv/
      - ./backend/:/app/
    env_file:
      - ./pps.env
    environment:
      - DEBUG=${DEBUG:-true}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-}
    command: >
      sh -c "
      pipenv run python manage.py makemigrations &&
      pipenv run python manage.py migrate &&
      pipenv run python manage.py runserver 0.0.0.0:8000
      "
    # gunicorn -c gunicorn_config.py server.wsgi:application --timeout 10800
    networks:
      - server_network
  # Frontend App
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:5173"
    expose:
      - "5173"
    networks:
      - server_network
    volumes:
      - ./frontend/:/app/
    command: >
      sh -c "
      npm run dev
      "
    depends_on:
      - backend
