networks:
  server_network:

services:
  # Banckend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    # volumes:
    #   - ./backend/:/app/
    env_file:
      - ./pps.env
    environment:
      - DEBUG=${DEBUG:-true}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-}
    command: >
      sh -c "
      ./.venv/bin/python manage.py makemigrations &&
      ./.venv/bin/python manage.py migrate &&
      ./.venv/bin/python manage.py runserver 0.0.0.0:8000
      "
    # gunicorn -c gunicorn_config.py server.wsgi:application --timeout 10800
    networks:
      - server_network
  # Frontend App
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
