# Generated by Django 5.1.6 on 2025-03-05 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('machine_type', models.CharField(choices=[('plastic_inyector', 'plastic inyector'), ('plastic_extruder', 'plastic extruder')], max_length=100, unique=True)),
                ('trained_employees', models.ManyToManyField(related_name='trained_machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'machine_type',
                'verbose_name_plural': 'machine_types',
                'db_table': 'machine_type',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('machine_number', models.CharField(max_length=100)),
                ('machine_title', models.CharField(max_length=100)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinetype')),
            ],
            options={
                'verbose_name': 'machine',
                'verbose_name_plural': 'machines',
                'db_table': 'machine',
                'unique_together': {('machine_number', 'machine_title')},
            },
        ),
    ]
