# Generated by Django 4.2 on 2024-01-21 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('machine_type', models.CharField(choices=[('plastic_inyector', 'plastic inyector'), ('plastic_extruder', 'plastic extruder')], help_text='Type of machine.', max_length=100, unique=True, verbose_name='Type of machine.')),
                ('trained_employees', models.ManyToManyField(related_name='trained_machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'machine type',
                'verbose_name_plural': 'machine types',
                'db_table': 'machine_type',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('machine_number', models.CharField(help_text='Number of the machine.', max_length=100, verbose_name='Number of the machine')),
                ('machine_title', models.CharField(help_text='Machine title.', max_length=100, verbose_name='Machine title.')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machinetype', verbose_name='machine')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machine',
                'db_table': 'machine',
                'unique_together': {('machine_number', 'machine_title')},
            },
        ),
    ]
