# Generated by Django 5.2 on 2025-06-16 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('produced_ammount', models.IntegerField(default=0)),
                ('shift_type', models.CharField(choices=[('maintenance', 'maintenance'), ('repair', 'repair'), ('production', 'producción')], max_length=20)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machine')),
                ('production_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorder')),
            ],
            options={
                'verbose_name': 'shift',
                'verbose_name_plural': 'shifts',
                'db_table': 'shift',
            },
        ),
    ]
