# Generated by Django 5.1.6 on 2025-03-05 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('identification', models.CharField(max_length=50, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('management', 'gerencia'), ('hr', 'recursos humanos'), ('quality', 'calidad'), ('prod_manager', 'jefe de producción'), ('prod', 'producción'), ('accounting', 'contabilidad')], default='prod', max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employees',
                'indexes': [models.Index(fields=['identification'], name='employees_identif_da5ea0_idx')],
            },
        ),
        migrations.CreateModel(
            name='OOO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ooo_type', models.CharField(choices=[('paid_leave', 'Vacaciones pagas'), ('non_paid_leave', 'Vacaciones no pagas'), ('work_accident', 'Accidente de trabajo'), ('non_work_accident', 'Accidente no relacionado con el trabajo'), ('paid_permit', 'permiso pago'), ('non_paid_permit', 'permiso no pago')], help_text='tiempo fuera de la oficina', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ooo',
                'verbose_name_plural': 'ooos',
                'db_table': 'ooo',
            },
        ),
    ]
