# Generated by Django 4.2 on 2023-11-29 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AlterModelOptions(
            name='ooo',
            options={'verbose_name': 'fuera de la oficina', 'verbose_name_plural': 'fuera de la oficina'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(help_text='cumpleaños del empleado', null=True, verbose_name='cumpleaños'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de unión a la plataforma'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identification',
            field=models.CharField(help_text='documento de identidad', max_length=50, unique=True, verbose_name='identificación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Último logueo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_names',
            field=models.CharField(help_text='apellidos del empleado', max_length=100, verbose_name='apellidos del empleado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='names',
            field=models.CharField(help_text='nombres del empleado', max_length=100, verbose_name='nombres del empleado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('management', 'gerencia'), ('hr', 'recursos humanos'), ('quality', 'calidad'), ('prod_manager', 'jefe de producción'), ('prod', 'producción'), ('accounting', 'contabilidad')], default='prod', help_text='rol del empleado', max_length=20, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='ooo',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='empleado'),
        ),
        migrations.AlterField(
            model_name='ooo',
            name='ooo_type',
            field=models.CharField(choices=[('paid_leave', 'Vacaciones pagas'), ('non_paid_leave', 'Vacaciones no pagas'), ('work_accident', 'Accidente de trabajo'), ('non_work_accident', 'Accidente no relacionado con el trabajo'), ('paid_permit', 'permiso pago'), ('non_paid_permit', 'permiso no pago')], help_text='tiempo fuera de la oficina', max_length=20, verbose_name='fuera de la oficina'),
        ),
    ]
