# Generated by Django 4.2 on 2023-12-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_ooo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ooo',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ooo',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
