# Generated by Django 4.2 on 2024-01-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_ooo_end_date_alter_ooo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identification',
            field=models.CharField(help_text='identification number', max_length=50, unique=True, verbose_name='identificación'),
        ),
    ]
