# Generated by Django 5.2 on 2025-06-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'production_order',
                'verbose_name_plural': 'production_orders',
                'db_table': 'production_order',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_ammount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionorder')),
            ],
            options={
                'verbose_name': 'production_order_item',
                'verbose_name_plural': 'production_order_items',
                'db_table': 'production_order_item',
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'sale_order',
                'verbose_name_plural': 'sale_orders',
                'db_table': 'sale_order',
            },
        ),
        migrations.CreateModel(
            name='QualityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateField()),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.saleorder')),
            ],
            options={
                'verbose_name': 'quality_evaluation',
                'verbose_name_plural': 'quality_evaluations',
                'db_table': 'quality_evaluation',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_ammount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.saleorder')),
            ],
            options={
                'verbose_name': 'sale_order_item',
                'verbose_name_plural': 'sale_order_items',
                'db_table': 'sale_order_item',
            },
        ),
        migrations.CreateModel(
            name='NonConformingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('non_conforming_product_ammount', models.IntegerField(default=0)),
                ('quality_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.qualityevaluation')),
                ('non_conforming_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.saleorderitem')),
            ],
            options={
                'verbose_name': 'non_conforming_product',
                'verbose_name_plural': 'non_conforming_products',
                'db_table': 'non_conforming_product',
            },
        ),
    ]
